// Admin

export const ORDER_TOTAL_ADMIN_LIST_REQUEST = 'ORDER_TOTAL_ADMIN_LIST_REQUEST';
export const ORDER_TOTAL_ADMIN_LIST_SUCCESS = 'ORDER_TOTAL_ADMIN_LIST_SUCCESS';
export const ORDER_TOTAL_ADMIN_LIST_FAIL = 'ORDER_TOTAL_ADMIN_LIST_FAIL';

export const ADMIN_TOTAL_USERS_LIST_REQUEST = 'ADMIN_TOTAL_USERS_LIST_REQUEST';
export const ADMIN_TOTAL_USERS_LIST_SUCCESS = 'ADMIN_TOTAL_USERS_LIST_SUCCESS';
export const ADMIN_TOTAL_USERS_LIST_FAIL = 'ADMIN_TOTAL_USERS_LIST_FAIL';
